SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600

MOVE_DISTANCE = 20
PADDING = 2

STARTING_POSITION = [(0, 0), (-MOVE_DISTANCE, 0), (-MOVE_DISTANCE * 2, 0)]
DIR_UP = 90
DIR_LEFT = 180
DIR_DOWN = 270
DIR_RIGHT = 0

ALIGNMENT = "center"
FONT = ("Arial", 17, "normal")
FONT_GAME_OVER = ("Arial", 30, "bold")

FOOD_SIZE_KOEF = .5
